/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Iwfh8mhaZAw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableBody, Table } from "@/components/ui/table"

export function component() {
  return (
    (<div
      className="w-full min-h-screen bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100">
      <header className="bg-gray-900 text-white py-4 px-6 dark:bg-gray-50">
        <div className="container mx-auto flex items-center justify-between">
          <h1 className="text-2xl font-bold">Train Schedule</h1>
          <div className="relative">
            <SearchIcon
              className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500 dark:text-gray-400" />
            <Input
              className="pl-10 pr-4 py-2 rounded-md bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent dark:focus:ring-gray-50"
              placeholder="Search trains..."
              type="text" />
          </div>
        </div>
      </header>
      <main className="container mx-auto py-8">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <Card>
            <CardHeader>
              <CardTitle>Train Tracking</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm/relaxed">
                Track the real-time location of your train and get updates on delays or changes.
              </p>
              <Button className="mt-4" size="sm" variant="outline">
                Track Train
              </Button>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Nearby Stations</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm/relaxed">Find the closest train stations to your location and plan your journey.</p>
              <Button className="mt-4" size="sm" variant="outline">
                View Stations
              </Button>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Ticket Pricing</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm/relaxed">
                Check the latest ticket prices for your desired route and plan your budget.
              </p>
              <Button className="mt-4" size="sm" variant="outline">
                View Pricing
              </Button>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Time Schedule</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm/relaxed">View the complete train schedule and plan your travel accordingly.</p>
              <Button className="mt-4" size="sm" variant="outline">
                View Schedule
              </Button>
            </CardContent>
          </Card>
        </div>
        <div className="mt-8">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Train #</TableHead>
                <TableHead>Destination</TableHead>
                <TableHead>Departure</TableHead>
                <TableHead>Arrival</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody />
          </Table>
        </div>
      </main>
    </div>)
  );
}

function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}
